### ISSUE TITLE
Upload images from remote locations

### ISSUE THREAD

**Issue by cmauro607** [tiberiusteng/financisto1-holo#2]
I have also been using the _Financisto_ application for many years with over 8000 entries, so I appreciate the improvements you have made to it, however, I appreciate you improving the functionality for uploading images to the new or existing record from remote locations.
It is an important functionality that so far I have not seen anyone implement in this excellent tool.
![image](https://github.com/tiberiusteng/financisto1-holo/assets/154445903/08b2f87e-86cd-4fca-b4a0-801f6495ecb7)

**Comment by tiberiusteng** [comment]
I don't think I will implement this anytime soon, but I'm open to discussion and share my thoughts so far:

Previously, when Financisto open or take a photo, it's stored in its app private storage, the database only contains its filename, the file itself doesn't got backed up from database exports, user have to use adb or other tool to create a backup for entire app private storage to include photos.

https://developer.android.com/training/data-storage/shared/photopicker

New version of Android have implemented a photo picker so a consumer app can get a URI for photos from other application, but this URI is temporary, the consumer is not guaranteed to have access to the chosen photo later, and the app providing photo doesn't know the photo is being used either, it could delete or move or change the URI of photo without considering there's users depending on it, so the consumer have to copy and storage the chosen photo itself.

When restoring from a backup file, the app only get access to the file user picked, so if we like to include photos in the backup, they have to be put into every backup files so that when restoring we have access to them. Photos are large, and daily backup of entire financial journaling photos album could be easily taking huge storage soon.

A solution could be storing database as-is, and individually saving photos taken, and ask user to put them together into a zip file should there's a need to restore in the future.

Storing URIs to remote photos could be another solution, but this method also lacks consistency (should user's album account have a need to migrate, the network is unavailable, etc).

**Comment by cmauro607** [comment]
Thanks for the reply.
