### ISSUE TITLE
Problem exporting csv format 

### ISSUE THREAD

**Issue by yrjoinc** [tiberiusteng/financisto1-holo#22]
Hi, exporting CSV format for Custom period is not working. I think only the option in filter for This month is working to export to Dropbox.
Also, it doesn't work for more than one month in past.
I mean, I trying to export information since 2008 and it only exported from last December 15.
Also, the option for exporting to Dropbox and Drive doesn't work.

**Comment by tiberiusteng** [comment]
I've just tried on my device and I got all my transactions back from ~2010 exported (with custom period) and uploaded to Dropbox and Google Drive.

You need to configure backup folder, link Dropbox and link Google Drive before trying to do export.

The CSV export code in its current form does not leave much log when anything unusual happened, so it's difficult to pinpoint where the problem is. If you can't get all your specified range exported, try check the transaction around where the export cutted off and see if it has anything strange.

If the app just crashes and you installed it from Google Play, I'll be able to look at crash log later and try to fix it.

**Comment by yrjoinc** [comment]
Hi, I already have linked Dropbox and Drive, but ai found out what was happening.
The error was in a special date with a transaction in one account because the account name had special character.
Once I changed the name, I could export the information.

Thanks

**Comment by tiberiusteng** [comment]
Ahh, thanks for the info, I'll try to create account with single quote and see how to handle it correctly.

**Comment by yrjoinc** [comment]
Thank you 👍
