### ISSUE TITLE
'Include into totals' not working for currencies other than USD

### ISSUE THREAD

**Issue by skwt** [tiberiusteng/financisto1-holo#45]
I use TWD as my default currency.
If I tick 'Include into totals' in any accounts which are not in USD, then an exclamation mark is displayed and it says "No exchange rate specified on XXX to calculate between XXX to XXX".
Accounts in USD are fine.
![Screenshot_20240620-114452](https://github.com/tiberiusteng/financisto1-holo/assets/37328620/3c62587f-181f-4c14-b888-4905b185c630)
![Screenshot_20240620-114503](https://github.com/tiberiusteng/financisto1-holo/assets/37328620/0bb129e9-ccfe-4717-ba5f-7a2ceef9e6aa)

**Comment by tiberiusteng** [comment]
實體 -> 匯率 按右下角更新鈕 下載一組(現在的)匯率就可以了
或是把外幣帳戶取消「計算到總財產中」
(它要有一筆外幣匯率才能算回預設貨幣)

In "Entities" -> "Exchange rates" press the refresh button on right-bottom to get latest exchange rates, and it should show.
Or you can deselect "Include into totals" in your foreign currency accounts
(since it need an exchange rate entry to calculate the home currency equivalent values of foreign currencies)

**Comment by skwt** [comment]
Thanks! It works.
